version: '3.3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: ./backend/.env

  backend:
    build: ./backend/
    env_file: ./backend/.env
    volumes:
      - media:/app/media/
      - static:/static/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: ./.env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static/

  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - static:/static/
      - media:/media/
