# Generated by Django 3.2.3 on 2024-04-05 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20240405_0741'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceVehicleType',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'cost',
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        verbose_name='Стоимость',
                    ),
                ),
                (
                    'service',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='service_vehicle_types',
                        to='service.service',
                        verbose_name='Услуга',
                    ),
                ),
                (
                    'vehicle_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='service_vehicle_types',
                        to='vehicle.vehicleortrailertype',
                        verbose_name='Тип ТС/ППЦ',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Услуга для типов ТС/ППЦ',
                'verbose_name_plural': 'Услуги для типов ТС/ППЦ',
                'ordering': ['service'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='vehicle_types',
            field=models.ManyToManyField(
                through='service.ServiceVehicleType',
                to='vehicle.VehicleOrTrailerType',
                verbose_name='Типы ТС/ППЦ',
            ),
        ),
    ]
