# Generated by Django 3.2.3 on 2024-04-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_servicevehicletype_employer_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicevehicletype',
            name='percentage_for_washer',
            field=models.IntegerField(default=30, verbose_name='% мойщика'),
            preserve_default=False,
        ),
    ]
