# Generated by Django 3.2.3 on 2024-04-18 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20240417_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceVehicleTypeLegalEntyty',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
                (
                    'employer_salary',
                    models.IntegerField(verbose_name='Оплата сотруднику'),
                ),
                (
                    'percentage_for_washer',
                    models.IntegerField(verbose_name='% мойщика'),
                ),
                (
                    'legal_entity',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='service_legal_entity',
                        to='service.service',
                        verbose_name='Владелец техники',
                    ),
                ),
                (
                    'service_vehicle_type',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='legal_entity_services',
                        to='service.service',
                        verbose_name='Услуга',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Услуга для типов ТС/ППЦ для юр. лиц',
                'verbose_name_plural': 'Услуги для типов ТС/ППЦ для юр. лиц',
                'ordering': ['legal_entity'],
            },
        ),
    ]
