# Generated by Django 3.2.3 on 2024-04-19 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_servicevehicletypelegalentyty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicevehicletypelegalentyty',
            name='service_vehicle_type',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='legal_entity_services',
                to='service.servicevehicletype',
                verbose_name='Услуга',
            ),
        ),
    ]
