# Generated by Django 3.2.3 on 2024-04-19 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparty', '0005_auto_20240413_0850'),
        (
            'service',
            '0007_alter_servicevehicletypelegalentyty_service_vehicle_type',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicevehicletypelegalentyty',
            name='legal_entity',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='service_legal_entity',
                to='counterparty.legalentity',
                verbose_name='Владелец техники',
            ),
        ),
    ]
