# Generated by Django 3.2.3 on 2024-04-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CompanyRequisites',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.TextField(verbose_name='Наименование')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('ogrn', models.TextField(verbose_name='ОГРН')),
                ('inn', models.TextField(verbose_name='ИНН')),
                ('okved', models.TextField(verbose_name='ОКВЭД')),
                (
                    'name_of_bank',
                    models.TextField(verbose_name='Наименование банка ИП'),
                ),
                (
                    'correspondent_account_of_bank',
                    models.TextField(
                        verbose_name='Корреспондентский счёт банка ИП'
                    ),
                ),
                ('bik_of_bank', models.TextField(verbose_name='БИК банка ИП')),
                (
                    'account_number_of_IP',
                    models.TextField(verbose_name='Расчётный счёт ИП'),
                ),
                ('email', models.TextField(verbose_name='E-mail')),
                ('phone', models.TextField(verbose_name='Телефон')),
                (
                    'director_name',
                    models.TextField(verbose_name='ФИО руководителя'),
                ),
            ],
            options={
                'verbose_name': 'Реквизиты организации',
                'verbose_name_plural': 'Реквизиты организации',
            },
        ),
    ]
