# Generated by Django 3.2.3 on 2024-04-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrequisites',
            name='account_number_of_IP',
            field=models.TextField(
                blank=True, null=True, verbose_name='Расчётный счёт ИП'
            ),
        ),
        migrations.AlterField(
            model_name='companyrequisites',
            name='address',
            field=models.TextField(
                blank=True, null=True, verbose_name='Адрес'
            ),
        ),
        migrations.AlterField(
            model_name='companyrequisites',
            name='bik_of_bank',
            field=models.TextField(
                blank=True, null=True, verbose_name='БИК банка ИП'
            ),
        ),
        migrations.AlterField(
            model_name='companyrequisites',
            name='correspondent_account_of_bank',
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name='Корреспондентский счёт банка ИП',
            ),
        ),
        migrations.AlterField(
            model_name='companyrequisites',
            name='director_name',
            field=models.TextField(
                blank=True, null=True, verbose_name='ФИО руководителя'
            ),
        ),
        migrations.AlterField(
            model_name='companyrequisites',
            name='email',
            field=models.TextField(
                blank=True, null=True, verbose_name='E-mail'
            ),
        ),
        migrations.AlterField(
            model_name='companyrequisites',
            name='inn',
            field=models.TextField(blank=True, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='companyrequisites',
            name='name',
            field=models.TextField(
                blank=True, null=True, verbose_name='Наименование'
            ),
        ),
        migrations.AlterField(
            model_name='companyrequisites',
            name='name_of_bank',
            field=models.TextField(
                blank=True, null=True, verbose_name='Наименование банка ИП'
            ),
        ),
        migrations.AlterField(
            model_name='companyrequisites',
            name='ogrn',
            field=models.TextField(blank=True, null=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='companyrequisites',
            name='okved',
            field=models.TextField(
                blank=True, null=True, verbose_name='ОКВЭД'
            ),
        ),
        migrations.AlterField(
            model_name='companyrequisites',
            name='phone',
            field=models.TextField(
                blank=True, null=True, verbose_name='Телефон'
            ),
        ),
    ]
