# Generated by Django 3.2.3 on 2024-04-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20240404_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrequisites',
            name='okpo',
            field=models.TextField(blank=True, null=True, verbose_name='ОКПО'),
        ),
    ]
