# Generated by Django 3.2.3 on 2024-04-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparty', '0002_auto_20240412_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='accountent_name',
            field=models.TextField(blank=True, null=True, verbose_name='ФИО бухгалтера'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='accountent_phone',
            field=models.TextField(blank=True, null=True, verbose_name='ФИО бухгалтера'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='mechanic_name',
            field=models.TextField(blank=True, null=True, verbose_name='ФИО механика'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='mechanic_phone',
            field=models.TextField(blank=True, null=True, verbose_name='ФИО механика'),
        ),
    ]
