# Generated by Django 3.2.3 on 2024-04-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparty', '0004_auto_20240413_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='account_number_of_IP',
            field=models.TextField(blank=True, default='', verbose_name='Расчётный счёт ИП'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='accountent_name',
            field=models.TextField(blank=True, default='', verbose_name='ФИО бухгалтера'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='accountent_phone',
            field=models.TextField(blank=True, default='', verbose_name='Телефон бухгалтера'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='bik_of_bank',
            field=models.TextField(blank=True, default='', verbose_name='БИК банка ИП'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='correspondent_account_of_bank',
            field=models.TextField(blank=True, default='', verbose_name='Корреспондентский счёт банка ИП'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='director_name',
            field=models.TextField(blank=True, default='', verbose_name='Должность/ФИО руководителя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='email',
            field=models.TextField(blank=True, default='', verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='inn',
            field=models.TextField(blank=True, default='', verbose_name='ИНН'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='kpp',
            field=models.TextField(blank=True, default='', verbose_name='КПП'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='mechanic_name',
            field=models.TextField(blank=True, default='', verbose_name='ФИО механика'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='mechanic_phone',
            field=models.TextField(blank=True, default='', verbose_name='Телефон механика'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='name',
            field=models.TextField(blank=True, default='', verbose_name='Наименование'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='name_of_bank',
            field=models.TextField(blank=True, default='', verbose_name='Наименование банка ИП'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='ogrn',
            field=models.TextField(blank=True, default='', verbose_name='ОГРН'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='okpo',
            field=models.TextField(blank=True, default='', verbose_name='ОКПО'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='okved',
            field=models.TextField(blank=True, default='', verbose_name='ОКВЭД'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='phone',
            field=models.TextField(blank=True, default='', verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
