# Generated by Django 3.2.3 on 2024-04-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparty', '0005_auto_20240413_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='short_name',
            field=models.TextField(
                blank=True, verbose_name='Короткое наименование'
            ),
        ),
    ]
