# Generated by Django 3.2.3 on 2024-04-06 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('MANAGER', 'Управляющий'), ('ADMINISTRATOR', 'Администратор'), ('WASHER', 'Мойщик')], default='ADMINISTRATOR', max_length=50, verbose_name='Должность')),
                ('name', models.CharField(max_length=250, verbose_name='Ф. И. О.')),
                ('short_name', models.CharField(max_length=250, verbose_name='Короткое имя')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь в БД')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
