# Generated by Django 3.2.3 on 2024-04-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='phone',
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name='Телефон'
            ),
        ),
    ]
