# Generated by Django 3.2.3 on 2024-04-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_alter_employer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={
                'ordering': ['name'],
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
