# Generated by Django 3.2.3 on 2024-04-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_alter_employer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='is_busy_working',
            field=models.BooleanField(default=False, verbose_name='Занят работой?'),
        ),
    ]
