# Generated by Django 3.2.3 on 2024-04-05 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counterparty', '0001_initial'),
        ('vehicle', '0003_auto_20240405_2223'),
        ('service', '0003_servicevehicletype_employer_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'order_datetime',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата/время заказа'
                    ),
                ),
                (
                    'order_close_datetime',
                    models.DateTimeField(verbose_name='Дата/время заказа'),
                ),
                (
                    'vehicle_owner_name',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name='ФИО/Наименование владельца ТС/ППЦ',
                    ),
                ),
                (
                    'vehicle_owner_phone',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name='Телефон владельца ТС/ППЦ',
                    ),
                ),
                (
                    'final_cost',
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        verbose_name='Итоговая стоимость',
                    ),
                ),
                (
                    'final_cost_for_employer_work',
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        verbose_name='Итоговая оплата работы сотрудника',
                    ),
                ),
                ('is_paid', models.BooleanField(verbose_name='Оплачен?')),
                (
                    'is_completed',
                    models.BooleanField(verbose_name='Завершен?'),
                ),
                (
                    'has_been_modifed_after_save',
                    models.BooleanField(
                        verbose_name='Был изменён после сохарнения?'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-order_datetime'],
            },
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'cost',
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        verbose_name='Cтоимость',
                    ),
                ),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='order_services',
                        to='order.order',
                        verbose_name='Заказ',
                    ),
                ),
                (
                    'service',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='order_services',
                        to='service.servicevehicletype',
                        verbose_name='Услуга для ТС/ППЦ',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Заказ-Услуга',
                'verbose_name_plural': 'Заказы-Услуги',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(
                through='order.OrderService',
                to='service.ServiceVehicleType',
                verbose_name='Услуга',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='orders',
                to='vehicle.vehicle',
                verbose_name='ТС/ППЦ',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle_owner',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='orders',
                to='counterparty.legalentity',
                verbose_name='Владелец ТС/ППЦ',
            ),
        ),
    ]
