# Generated by Django 3.2.3 on 2024-04-21 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_vehiclemodel'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='if_tractor_trailer',
            new_name='is_tractor_trailer',
        ),
        migrations.AddField(
            model_name='order',
            name='trailer_model',
            field=models.CharField(
                blank=True, max_length=150, verbose_name='Модель ППЦ'
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(
                choices=[
                    ('CASH', 'Наличные'),
                    ('TRANSFER', 'Перевод'),
                    ('CARD', 'Карта'),
                    ('CONTRACT', 'Договор'),
                ],
                default='CASH',
                max_length=50,
                verbose_name='Метод оплаты',
            ),
        ),
        migrations.RemoveField(
            model_name='order',
            name='vehicle',
        ),
        migrations.CreateModel(
            name='OrderVehicle',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='vehicles_in_order',
                        to='order.order',
                        verbose_name='Заказ-ТС',
                    ),
                ),
                (
                    'vehicle',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='vehicle_orders',
                        to='vehicle.vehicle',
                        verbose_name='ТС/ППЦ',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle',
            field=models.ManyToManyField(
                through='order.OrderVehicle',
                to='vehicle.Vehicle',
                verbose_name='Услуга',
            ),
        ),
    ]
