# Generated by Django 3.2.3 on 2024-04-23 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_servicevehicletypelegalentyty_legal_entity'),
        ('vehicle', '0008_vehiclemodel'),
        ('order', '0002_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='vehicle_type',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='vehicle.vehicleortrailertype',
                verbose_name='Тип ТС/ППЦ',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='service',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='services_in_order',
                to='service.service',
                verbose_name='Услуга для ТС/ППЦ',
            ),
        ),
    ]
