# Generated by Django 3.2.3 on 2024-04-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20240423_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='legal_entity_service',
            field=models.BooleanField(default=False, verbose_name='По договору?'),
        ),
    ]
