# Generated by Django 3.2.3 on 2024-04-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderservice_legal_entity_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=255, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='vehicle_plate_number',
            field=models.CharField(default='', max_length=25, verbose_name='Гос. номер'),
            preserve_default=False,
        ),
    ]
