# Generated by Django 3.2.3 on 2024-04-23 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_vehiclemodel'),
        ('order', '0005_auto_20240423_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderservice',
            name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='orderservice',
            name='vehicle_plate_number',
        ),
        migrations.RemoveField(
            model_name='orderservice',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='orderservice',
            name='vehicle',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='vehicle.vehicle',
                verbose_name='ТС/ППЦ',
            ),
        ),
    ]
