# Generated by Django 3.2.3 on 2024-04-04 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='VehicleOrTrailerClass',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=255, verbose_name='Наименование'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Класс ТС или ППЦ',
                'verbose_name_plural': 'Классы ТС или ППЦ',
            },
        ),
        migrations.CreateModel(
            name='VehicleOrTrailerType',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=255, verbose_name='Наименование'
                    ),
                ),
                (
                    'vehicle_class',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='vehicle.vehicleortrailerclass',
                        verbose_name='Класс ТС или ППЦ',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Тип ТС или ППЦ',
                'verbose_name_plural': 'Типы ТС или ППЦ',
            },
        ),
    ]
