# Generated by Django 3.2.3 on 2024-04-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20240412_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleortrailertype',
            name='is_tractor_with_trailer',
            field=models.BooleanField(
                default=False, verbose_name='Тягач с прицепом?'
            ),
        ),
    ]
