# Generated by Django 3.2.3 on 2024-04-13 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_auto_20240413_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_class',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='vehicles',
                to='vehicle.vehicleortrailertype',
                verbose_name='Класс ТС или ППЦ',
            ),
        ),
    ]
