# Generated by Django 3.2.3 on 2024-04-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_auto_20240413_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Модель ТС или ППЦ',
                'verbose_name_plural': 'Модели ТС или ППЦ',
                'ordering': ['name'],
            },
        ),
    ]
